name: CD
on:
  push:
    branches: 
      - main
      - fix/*
      - feat/*
  pull_request:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: dual

      - name: testing ipv6 connection
        run: |
          curl -m 9 --ipv6 --verbose https://google.com

      - name: the deployment
        timeout-minutes: 10
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IPV6_VPS }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          protocol: tcp6
          port: 22
          command_timeout: 30s
          script: |
            whoami
            cd go-actions-test
            git pull
            docker compose up -d
